name: Build Docker image

on:
  push:
    paths:
      - '*.py'
      - 'Dockerfile'
      - '.github/workflows/docker_build.yaml'
    branches:
      - main

permissions:
  packages: write

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/dodancs/squid-log-analyzer:${{ github.ref_name }},ghcr.io/dodancs/squid-log-analyzer:latest
